modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="scamolors_gadgets"
version="-1.0R"
displayName="Scamolor's Gadgets"
credits="Made by Scamolor"
displayURL="https://github.com/Scamolor"
logoFile="logo.png"
authors="Scamolor"
description='''
A mod that adds some new stuff
'''

[[dependencies.scamolors_gadgets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




